syntax = "proto3";

package channels;
option java_package = "com.viscord.message_service.grpc";
option java_multiple_files = true;
option java_outer_classname = "ChannelProto";

import "permissions.proto";

service ChannelsService {
  rpc AcknowledgeMessage (AcknowledgeMessageRequest) returns (AcknowledgeMessageResponse);
  rpc GetDMChannels (GetDMChannelsRequest) returns (GetDMChannelsResponse);
  rpc GetChannelById (GetChannelByIdRequest) returns (GetChannelByIdResponse);
  rpc IsUserChannelParticipant (IsUserChannelParticipantRequest) returns (IsUserChannelParticipantResponse);
  rpc CanUserSendMessage (CanUserSendMessageRequest) returns (CanUserSendMessageResponse);
  rpc CanUserGetChannelMessages (CanUserGetChannelMessagesRequest) returns (CanUserGetChannelMessagesResponse);
  rpc CanUserDeleteMessage (CanUserDeleteMessageRequest) returns (CanUserDeleteMessageResponse);
  rpc CheckPermission (CheckPermissionRequest) returns (CheckPermissionResponse);
}

message AcknowledgeMessageRequest {
  string userId = 1;
  string channelId = 2;
  string messageId = 3;
}

message AcknowledgeMessageResponse {
  int32 status = 1;
  string message = 2;
}

message GetDMChannelsRequest {
  string userId = 1;
}

message GetDMChannelsResponse {
  int32 status = 1;
  repeated Channel data = 2;
}

message GetChannelByIdRequest {
  string channelId = 1;
  string userId = 2;
}


message GetChannelByIdResponse {
  int32 status = 1;
  Channel data = 2;
}

message IsUserChannelParticipantRequest {
  string userId = 1;
  string channelId = 2;
}

message IsUserChannelParticipantResponse {
  int32 status = 1;
  string message = 2;
}

message CanUserSendMessageRequest {
  string userId = 1;
  string channelId = 2;
}

message CanUserSendMessageResponse {
  int32 status = 1;
  bool data = 2;
  string message = 3;
}

message CanUserDeleteMessageRequest {
  string userId = 1;
  string channelId = 2;
  string messageAuthorId = 4;
}

message CanUserDeleteMessageResponse {
  bool allowed = 1;
}


message CheckPermissionRequest {
  string userId = 1;
  string channelId = 2;
  repeated permissions.Permission permissions = 3;
}

message CheckPermissionResponse {
  bool allowed = 1;
}


message CanUserGetChannelMessagesRequest {
  string userId = 1;
  string channelId = 2;
}

message CanUserGetChannelMessagesResponse {
  int32 status = 1;
  bool data = 2;
  string message = 3;
}

enum ChannelType {
  TEXT = 0;
  VOICE = 1;
  CATEGORY = 2;
  DM = 3;
}

enum UserStatus {
  OFFLINE = 0;
  ONLINE = 1;
  INVISIBLE = 2;
  IDLE = 3;
  DO_NOT_DISTURB = 4;
}

message UserProfile {
  string id = 1;
  string displayName = 2;
  string username = 3;
  string pronouns = 4;
  string bio = 5;
  UserStatus status = 6;
  string avatarURL = 7;
  string defaultAvatarURL = 8;
  string createdAt = 9;
  string updatedAt = 10;
}

message Guild {
  string id = 1;
  string name = 2;
  string ownerId = 3;
  string iconURL = 4;
  repeated Channel channels = 5;
  string createdAt = 6;
  string updatedAt = 7;
  repeated GuildMember members = 8;
  repeated Role roles = 9;
}

message UserChannelState {
  string lastReadId = 1;
  int32 unreadCount = 2;
  int32 mentionCount = 3;
}

message Channel {
  string id = 1;
  string name = 2;
  ChannelType type = 3;
  string createdAt = 5;
  string updatedAt = 6;
  Channel parent = 7;
  Guild guild = 8;
  repeated UserProfile recipients = 9;
  string lastMessageId = 10;
  string guildId = 11;
  UserChannelState userChannelState = 12;
  repeated PermissionOverwrite permissionOverwrites = 13;
  bool isSynced = 14;
}

message Role {
  string id = 1;
  string name = 2;
  string permissions = 3;
  int32 position = 4;
  bool isHoisted = 5;
  string guildId = 6;
  int32 color = 7;
}

message GuildMember {
  string userId = 1;
  repeated string roles = 2;
  UserProfile profile = 3;
}

message PermissionOverwrite {
  string allow = 2;
  string deny = 3;
  string targetId = 4;
  string targetType = 5;
  string channelId = 6;
}